// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4BP-aC9fyuqK2rgxgx4ISzmaD3zxoVi4',
    appId: '1:1008867138851:web:f4f77ffdad7dfb1afe8096',
    messagingSenderId: '1008867138851',
    projectId: 'chat-bot-uor9',
    authDomain: 'chat-bot-uor9.firebaseapp.com',
    storageBucket: 'chat-bot-uor9.appspot.com',
    measurementId: 'G-HYQB3F2QM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfIZ7Gniz-lIyvL-HsuU2qmbOH01VB_g',
    appId: '1:1008867138851:android:75481b232643a277fe8096',
    messagingSenderId: '1008867138851',
    projectId: 'chat-bot-uor9',
    storageBucket: 'chat-bot-uor9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLKvrmTEmV7XmTSO3CpnS75UPu1COUljk',
    appId: '1:1008867138851:ios:a34e11908d20906efe8096',
    messagingSenderId: '1008867138851',
    projectId: 'chat-bot-uor9',
    storageBucket: 'chat-bot-uor9.appspot.com',
    iosBundleId: 'com.example.skanmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLKvrmTEmV7XmTSO3CpnS75UPu1COUljk',
    appId: '1:1008867138851:ios:a34e11908d20906efe8096',
    messagingSenderId: '1008867138851',
    projectId: 'chat-bot-uor9',
    storageBucket: 'chat-bot-uor9.appspot.com',
    iosBundleId: 'com.example.skanmed',
  );
}
